import type { Metadata } from "next";
import { Figtree, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GithubLogoIcon } from "@phosphor-icons/react/dist/ssr";
import Link from "next/link";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { Button } from "@/components/ui/button";
import { ButtonGroup } from "@/components/ui/button-group";
import { SrOnly } from "@/components/ui/sr-only";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={figtree.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          storageKey="portfolio-theme"
          enableSystem
          disableTransitionOnChange
          enableColorScheme
        >
          <header className="flex justify-between p-4">
            <Link
              href="/"
              className="text-xl md:text-2xl lg:text-3xl font-bold uppercase"
            >
              <span>William</span>
              <br />
              <span>Pei</span>
            </Link>
            <ButtonGroup>
              <ButtonGroup>
                <Tooltip>
                  <TooltipTrigger render={<ThemeToggle variant="ghost" />} />
                  <TooltipContent>Change theme</TooltipContent>
                </Tooltip>
              </ButtonGroup>
              <ButtonGroup>
                <Tooltip>
                  <a
                    href="https://github.com/draekien/portfolio"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <TooltipTrigger render={<Button variant="ghost" />}>
                      <GithubLogoIcon />
                      <SrOnly>View Repository</SrOnly>
                    </TooltipTrigger>
                  </a>
                  <TooltipContent>View repository on GitHub</TooltipContent>
                </Tooltip>
              </ButtonGroup>
            </ButtonGroup>
          </header>
          <main className="p-4">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
